<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>duHastNet.UI.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Utils.23.0.0.3">
      <HintPath>..\_References\Utils.23.0.0.3.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
