<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
	<AssemblyVersion>1.0.3.0</AssemblyVersion>
	<FileVersion>1.0.3.0</FileVersion>
	<Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\duHastNet.DocManager.UI.Shared\duHastNet.DocManager.UI.Shared.csproj" />
    <!-- utility dll reference -->
    <Reference Include="Utils.25.0.1.1">
      <HintPath>..\\..\\..\\_References\\duHast\\Utils.25.0.1.1.dll</HintPath>
      <Private>True</Private>
    </Reference>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Icon.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
