<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\duHastNet.DocManager\duHastNet.DocManager.Core\duHastNet.DocManager.Core.csproj" />
    <ProjectReference Include="..\duHastNet.DocManager\duHastNet.DocManager.UI.Shared\duHastNet.DocManager.UI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <!-- utility dll reference -->
    <Reference Include="Utils.25.0.1.1">
      <HintPath>..\\..\\_References\\duHast\\Utils.25.0.1.1.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\Merge\MatchedDocs\" />
    <Folder Include="ViewModels\Merge\MergeLog\" />
    <Folder Include="ViewModels\Settings\CloudDocManager\CloudProviderControls\" />
    <Folder Include="ViewModels\Settings\Database\" />
    <Folder Include="ViewModels\Settings\CurrentFolder\" />
  </ItemGroup>

</Project>
