<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
	<!-- Copy NuGet dependencies to output -->
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

	<Target Name="CopyNativeDependencies" AfterTargets="Build">
		<ItemGroup>
			<NativeLibs Include="..\duHastNet.DocManager.Core\duHastNet.DocManager.Core\bin\x64\$(Configuration)\net8.0-windows\runtimes\win-x64\native\*.dll" />
		</ItemGroup>
		<Copy SourceFiles="@(NativeLibs)" DestinationFolder="$(OutputPath)\runtimes\win-x64\native" SkipUnchangedFiles="true" />
	</Target>

  <ItemGroup>
    <ProjectReference Include="..\duHastNet.DocManager.Core\duHastNet.DocManager.Core.csproj" />
    <ProjectReference Include="..\duHastNet.DocManager.UI.Shared\duHastNet.DocManager.UI.Shared.csproj" />
	  <Reference Include="RevitAPI">
		  <HintPath>..\\..\\..\\_References\\Autodesk\\RevitAPI.dll</HintPath>
		  <Private>False</Private>
	  </Reference>
	  <Reference Include="RevitAPIUI">
		  <HintPath>..\\..\\..\\_References\\Autodesk\\RevitAPIUI.dll</HintPath>
		  <Private>False</Private>
	  </Reference>
	  <Reference Include="CefSharp.Core">
		  <HintPath>..\\..\\..\\_References\\Autodesk\\CefSharp.Core.dll</HintPath>
		  <Private>False</Private>
	  </Reference>
	  <Reference Include="CefSharp">
		  <HintPath>..\\..\\..\\_References\\Autodesk\\CefSharp.dll</HintPath>
		  <Private>False</Private>
	  </Reference>
	  <Reference Include="CefSharp.Wpf">
		  <HintPath>..\\..\\..\\_References\\Autodesk\\CefSharp.Wpf.dll</HintPath>
		  <Private>False</Private>
	  </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

</Project>
