project_id = "sample-project"
name = "Sample Hospital Job"
is_default = false
room_label = [
    "$name",
    "Area",
    "$id",
]
milestones = []
drofus_fields = []
colour_plans = []

[sources.drofus]
type = "file"
path = "../drofus.csv"

[[hierarchy]]
name = "Building"
code_property = "d_building_code"
name_property = "d_building_name"

[[hierarchy]]
name = "Department"
code_property = "Department"

[[builtin_properties]]
canonical = "Area"

[builtin_properties.by_source]
revit = "Area"

[[builtin_properties]]
canonical = "Number"

[builtin_properties.by_source]
revit = "Number"

[[builtin_properties]]
canonical = "Department"

[builtin_properties.by_source]
revit = "Department"
